POST {{u}}/auth/signup
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data;"

email=laciferin@gmail.com
--WebAppBoundary--

###

POST {{u}}/auth/signup
Content-Type: application/json


###

POST {{u}}/auth/signin
Content-Type: application/json

{}

###
GET {{u}}
Accept: application/json


