PATCH {{u}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjg4MDgwMDM3NzM2MjIxOTAwMCwiZW1haWwiOiJoaXJvQGdtYWlsLmNvbSIsImlhdCI6MTY4ODg2OTM0NiwiZXhwIjoxNjg4ODcyOTQ2fQ.FLYpqmp-2NiwETAcmaDmd3VG1M8_vZCmoFQxb5SSf_8

{
  "firstName": "Baymax",
  "lastName": "Hamada"
}

###
GET {{u}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjg4MDgwMDM3NzM2MjIxOTAwMCwiZW1haWwiOiJoaXJvQGdtYWlsLmNvbSIsImlhdCI6MTY4ODg2OTM0NiwiZXhwIjoxNjg4ODcyOTQ2fQ.FLYpqmp-2NiwETAcmaDmd3VG1M8_vZCmoFQxb5SSf_8

Accept: application/json

###
POST {{u}}/auth/signup
Content-Type: application/x-www-form-urlencoded

email=hiro@gmail.com&password=hiHelloGiberrish@123


###

POST {{u}}/auth/signin
Content-Type: application/x-www-form-urlencoded

email=hiro@gmail.com&password=hiHelloGiberrish@123


###
GET {{u}}
Accept: application/json

