GET {{u}}/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjg4MDczNjI3Mzg5MjE0NzIwMCwiZW1haWwiOiJoaXJvQGdtYWlsLmNvbSIsImlhdCI6MTY4ODg2MTcxNCwiZXhwIjoxNjg4ODY1MzE0fQ.3nmbdfM1XYScxCPZaeNIzoZs4aX4k4ejKRksRSSP5mQ

Accept: application/json

###
POST {{u}}/auth/signup
Content-Type: application/x-www-form-urlencoded

email=hiro@gmail.com&password=hiHelloGiberrish@123


###

POST {{u}}/auth/signin
Content-Type: application/x-www-form-urlencoded

email=hiro@gmail.com&password=hiHelloGiberrish@123


###
GET {{u}}
Accept: application/json

