GET {{u}}/users/me
Accept: application/json

###
POST {{u}}/auth/signup
Content-Type: application/x-www-form-urlencoded

email=hiro@gmail.com&password=hiHelloGiberrish@123


###

POST {{u}}/auth/signin
Content-Type: application/x-www-form-urlencoded

email=hiro@gmail.com&password=hiHelloGiberrish@123


###
GET {{u}}
Accept: application/json


